name: PR for release branch
on:
  push:
    branches:
      - develop
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create PR to other branches, on commits to a branch
        uses: gorillio/github-action-cherry-pick@1.2
        with:
          pr_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITBOT_EMAIL: yo@rilldata.com
          DRY_RUN: false
